In [2]:
import numpy as np

In [ ]:
printing of numpy arrays

In [3]:
a = np.arange(6) #1D array

a

array([0, 1, 2, 3, 4, 5])

In [4]:
a.shape

(6,)

In [5]:
b = np.arange(12).reshape(4,3) #2D arrays

b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
b.shape

(4, 3)

In [7]:
c = np.arange(24).reshape(2,3,4)

c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
c.shape

(2, 3, 4)

In [ ]:
Arithmetic operations

In [3]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [4]:
a+b

array([15, 15, 15])

In [5]:
a-b

array([5, 5, 5])

In [6]:
a*b

array([50, 50, 50])

In [7]:
a**2

array([100, 100, 100], dtype=int32)

In [8]:
b**3

array([125, 125, 125], dtype=int32)

In [9]:
a/b

array([2., 2., 2.])

In [10]:
a<20

array([ True,  True,  True])

In [14]:
a>20

False

In [ ]:
Modifying an existing array, then creating a new one

In [16]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [28]:
a*=3
a

array([590490, 590490, 590490])

In [29]:
a

array([590490, 590490, 590490])

In [30]:
b+=a
b

array([590495, 590495, 590495])

In [ ]:
unary operators

In [33]:
ages = np.array([12,14,15,19,22,24,22,29,44,45,57,23])

In [34]:
ages.sum()

326

In [35]:
ages.min()

12

In [37]:
ages.max()


57

In [38]:
number = np.arange(12).reshape(3,4)
number


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
req: to find the sum on row wise and column wise

In [ ]:
**axis1 = rows
**axis0 = colums

In [39]:
number.sum(axis=1)

array([ 6, 22, 38])

In [40]:
number.sum(axis=0)

array([12, 15, 18, 21])