In [ ]:
Introduction to numpy

In [2]:
!pip install numpy

In [ ]:
data type in the numpy ----> ndarray-----> it is similar to a list.

In [ ]:
ndarray is more efficient and needs minimum space

In [ ]:
creating numpy array:

In [5]:
import numpy as np

In [6]:
array_one = np.array([1,2,3,4])

array_one

array([1, 2, 3, 4])

In [7]:
type(array_one)

numpy.ndarray

In [8]:
numbers = [1,2,3,4,5]

In [9]:
array_two = np.array(numbers)

array_two

array([1, 2, 3, 4, 5])

In [10]:
type(array_two)

numpy.ndarray

In [11]:
array_of_zeros = np.zeros([3,4])

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
array_of_ones = np.ones([2,3])

array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
array_of_newones = np.ones([3,4], dtype=np.int16)

array_of_newones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [14]:
array_eye = np.eye(3)

array_eye


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
req: to create an empty array

In [20]:
array_empty = np.empty ([2,3])

array_empty


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
req: I want to print only even and odd numbers in different arrays

In [23]:
array_of_even = np.arange(2,30,2)

array_of_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
array_of_odd = np.arange(3,30,2)

array_of_odd

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])